### ISSUE TITLE
如何扩展到Stable-Diffusion-Webui的Animation中？

### ISSUE THREAD

**Issue by lishijia2740** [Winfredy/SadTalker#43]

**Comment by vinthony** [comment]
same as #11, still tunning sadtalker as an sd extension.

**Comment by vinthony** [comment]
Add sd-extension.  Just install it in extensions -> install from URL -> https://github.com/Winfredy/SadTalker, which may take several minutes to download the models automatically.

**Comment by gtbloody** [comment]
装好扩展之后在webui的什么位置运行？我没有找到页签或者是选项卡

**Comment by vinthony** [comment]
> 装好扩展之后在webui的什么位置运行？我没有找到页签或者是选项卡

参考：https://github.com/Winfredy/SadTalker#sd-webui-extension

**Comment by gtbloody** [comment]
我对比了你们的界面，选项卡没有出现，看了启动日志，有一条
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "D:\novelai-webui-aki-v3\py310\python.exe" -m pip install face-alignment==1.3.5 --prefer-binary
Error code: 1
是不是因为我用的秋叶的整合包，python环境和你们的不一致导致的啊

**Comment by vinthony** [comment]
windows我跑通了的。可能国内使用需要一些`魔法`.

**Comment by gtbloody** [comment]
> windows我跑通了的。可能国内使用需要一些`魔法`.

我看起来不是魔法的问题，我已经开了tun模式了，我看启动日志Installing requirements for SadTalker前面都是成功的，方不方便我日志发上来帮我看一下

**Comment by vinthony** [comment]
> > windows我跑通了的。可能国内使用需要一些`魔法`.
> 
> 我看起来不是魔法的问题，我已经开了tun模式了，我看启动日志Installing requirements for SadTalker前面都是成功的，方不方便我日志发上来帮我看一下

可以的。

**Comment by gtbloody** [comment]
Installing requirements for SadTalker
Error executing callback ui_tabs_callback for D:\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 62, in on_ui_tabs
    install()
  File "D:\novelai-webui-aki-v3\extensions\SadTalker\scripts\extension.py", line 49, in install
    launch.run_pip("install "+ v, "requirements for SadTalker")
  File "D:\novelai-webui-aki-v3\launch.py", line 145, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\novelai-webui-aki-v3\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "D:\novelai-webui-aki-v3\py310\python.exe" -m pip install face-alignment==1.3.5 --prefer-binary
Error code: 1
stdout: Collecting face-alignment==1.3.5

  Using cached face_alignment-1.3.5-py2.py3-none-any.whl

Requirement already satisfied: numpy in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (1.24.2)

Requirement already satisfied: tqdm in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (4.64.1)

Requirement already satisfied: opencv-python in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (4.6.0.66)

Requirement already satisfied: scipy>=0.17 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (1.9.3)

Requirement already satisfied: scikit-image in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (0.19.2)

Requirement already satisfied: numba in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (0.56.4)

Requirement already satisfied: torch in d:\novelai-webui-aki-v3\py310\lib\site-packages (from face-alignment==1.3.5) (2.0.0+cu118)

Requirement already satisfied: setuptools in d:\novelai-webui-aki-v3\py310\lib\site-packages (from numba->face-alignment==1.3.5) (65.6.0)

Collecting numpy

  Using cached numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)

Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from numba->face-alignment==1.3.5) (0.39.1)

Requirement already satisfied: packaging>=20.0 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (21.3)

Requirement already satisfied: PyWavelets>=1.1.1 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (1.4.1)

Requirement already satisfied: imageio>=2.4.1 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (2.22.4)

Requirement already satisfied: tifffile>=2019.7.26 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (2022.10.10)

Requirement already satisfied: networkx>=2.2 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (3.0)

Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from scikit-image->face-alignment==1.3.5) (9.4.0)

Requirement already satisfied: sympy in d:\novelai-webui-aki-v3\py310\lib\site-packages (from torch->face-alignment==1.3.5) (1.11.1)

Requirement already satisfied: typing-extensions in d:\novelai-webui-aki-v3\py310\lib\site-packages (from torch->face-alignment==1.3.5) (4.5.0)

Requirement already satisfied: filelock in d:\novelai-webui-aki-v3\py310\lib\site-packages (from torch->face-alignment==1.3.5) (3.10.6)

Requirement already satisfied: jinja2 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from torch->face-alignment==1.3.5) (3.1.2)

Requirement already satisfied: colorama in d:\novelai-webui-aki-v3\py310\lib\site-packages (from tqdm->face-alignment==1.3.5) (0.4.6)

Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from packaging>=20.0->scikit-image->face-alignment==1.3.5) (3.0.9)

Requirement already satisfied: MarkupSafe>=2.0 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from jinja2->torch->face-alignment==1.3.5) (2.1.2)

Requirement already satisfied: mpmath>=0.19 in d:\novelai-webui-aki-v3\py310\lib\site-packages (from sympy->torch->face-alignment==1.3.5) (1.3.0)

Installing collected packages: numpy, face-alignment

  Attempting uninstall: numpy

    Found existing installation: numpy 1.24.2

    Uninstalling numpy-1.24.2:

      Successfully uninstalled numpy-1.24.2

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\novelai-webui-aki-v3\\py310\\Lib\\site-packages\\~-6py\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'

Consider using the `--user` option or check the permissions.

CUDA SETUP: Loading binary D:\novelai-webui-aki-v3\py310\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

**Comment by vinthony** [comment]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/4397546/230706699-8fcc6147-041a-4e0a-bd66-686ffbf7a617.png">

https://github.com/Winfredy/SadTalker/blob/8a99c8bbe792e5671e7eace9588e3104a23414a3/scripts/extension.py#L49

可能可以在这一行添加 --user，变成:

```python
launch.run_pip("install --user "+ v, "requirements for SadTalker") 
```

**Comment by gtbloody** [comment]
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/4397546/230706699-8fcc6147-041a-4e0a-bd66-686ffbf7a617.png">
> 
> https://github.com/Winfredy/SadTalker/blob/8a99c8bbe792e5671e7eace9588e3104a23414a3/scripts/extension.py#L49
> 
> 可能可以在这一行添加 --user，变成:
> 
> ```python
> launch.run_pip("install --user "+ v, "requirements for SadTalker") 
> ```

还是装不上，感觉网络好像也有问题，不行我就不用插件了，分开单独用吧

**Comment by gtbloody** [comment]
我请chatgpt看了我的错误代码，是我在执行extension.py时，依赖库装不上，有没有国内的镜像库可以装依赖呢
具体错误如下
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "D:\novelai-webui-aki-v3\extensions\Sadtallker\scripts\extension.py", line 62, in on_ui_tabs
    install()
  File "D:\novelai-webui-aki-v3\extensions\Sadtallker\scripts\extension.py", line 49, in install
    launch.run_pip("install --user"+ v, "requirements for SadTalker")
  File "D:\novelai-webui-aki-v3\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\novelai-webui-aki-v3\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for SadTalker

**Comment by Chantinoo** [comment]
能帮忙看下这是什么问题吗？

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI

Launching Web UI with arguments: --theme dark --xformers --autolaunch --api
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\SD\01-01HH\novelai-webui-aki-v3A\extensions\Stable-Diffusion-Webui-Civitai-Helper-main\setting.json
Civitai Helper: No setting file, use default
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

Loading weights [135bb58293] from D:\SD\01-01HH\novelai-webui-aki-v3A\models\Stable-diffusion\revAnimated_reva1.safetensors
Creating model from config: D:\SD\01-01HH\novelai-webui-aki-v3A\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\SD\01-01HH\novelai-webui-aki-v3A\models\VAE\clearvae_main.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(4): bad-picture-chill-75v, badhardv5, easynegative, ng_deepnegative_v1_75t
Model loaded in 3.4s (create model: 0.4s, apply weights to model: 0.6s, apply half(): 0.6s, move model to device: 0.8s, load textual inversion embeddings: 0.9s).
face-alignment False
Installing requirements for SadTalker
imageio True
imageio-ffmpeg False
Installing requirements for SadTalker
librosa True
pydub True
scipy True
tqdm True
yacs True
pyyaml False
Installing requirements for SadTalker
dlib True
gfpgan True
Error executing callback ui_tabs_callback for D:\SD\01-01HH\novelai-webui-aki-v3A\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\extensions\SadTalker\scripts\extension.py", line 68, in on_ui_tabs
    install()
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\extensions\SadTalker\scripts\extension.py", line 64, in install
    download_model(paths.script_path+'/extensions/SadTalker/checkpoints')
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\extensions\SadTalker\scripts\extension.py", line 14, in download_model
    snapshot_download(repo_id=REPO_ID, local_dir=local_dir, local_dir_use_symlinks=True)
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\SD\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: snapshot_download() got an unexpected keyword argument 'local_dir'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.
Startup time: 37.7s (import gradio: 3.2s, import ldm: 1.1s, other imports: 2.4s, list extensions: 3.1s, list SD models: 0.1s, setup codeformer: 0.2s, load scripts: 2.9s, load SD checkpoint: 3.6s, create ui: 20.6s, gradio launch: 0.5s).

**Comment by 850977164** [comment]
> > <img alt="image" width="996" src="https://user-images.githubusercontent.com/4397546/230706699-8fcc6147-041a-4e0a-bd66-686ffbf7a617.png">
> > https://github.com/Winfredy/SadTalker/blob/8a99c8bbe792e5671e7eace9588e3104a23414a3/scripts/extension.py#L49
> > 可能可以在这一行添加 --user，变成:
> > ```python
> > launch.run_pip("install --user "+ v, "requirements for SadTalker") 
> > ```
> 
> 还是装不上，感觉网络好像也有问题，不行我就不用插件了，分开单独用吧



> 我对比了你们的界面，选项卡没有出现，看了启动日志，有一条 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。 Command: "D:\novelai-webui-aki-v3\py310\python.exe" -m pip install face-alignment==1.3.5 --prefer-binary Error code: 1 是不是因为我用的秋叶的整合包，python环境和你们的不一致导致的啊

我也遇到了同样的问题，你解决这个问题了吗
