### ISSUE TITLE
error with VideoCapture

### ISSUE THREAD

**Issue by yuyu82** [Winfredy/SadTalker#52]
I followed the instructions to install and generate a video, but the following error occurred How can I resolve this issue? The video itself is output and complete.

./checkpoints\epoch_20.pth
./checkpoints\auido2pose_00140-model.pth
./checkpoints\auido2exp_00300-model.pth
./checkpoints\facevid2vid_00189-model.pth.tar
./checkpoints\mapping_00229-model.pth.tar
[ERROR:0@0.007] global cap_ffmpeg_impl.hpp:1223 open Could not find decoder for codec_id=61
[ERROR:0@0.007] global cap_ffmpeg_impl.hpp:1272 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture

**Comment by vinthony** [comment]
it might be because the reason of FFmpeg on windows where we do not have the windows machine to test. you may try to generate the video via our online demo.

**Comment by bobby-chiu** [comment]
@vinthony @yuyu82 I met the path split bug, it will be breakdown  if given the input argments as `--source_image ./test.png`, and worked fine as `--source_image test.png`. The issue is quite simple to fix, Try below if it is your case.

Change the code in the `preprocess.py` :
`        elif input_path.split('.')[1] in ['jpg', 'png', 'jpeg']:`
to
`        elif input_path.split('.')[-1] in ['jpg', 'png', 'jpeg']:`
