### ISSUE TITLE
Different style

### ISSUE THREAD

**Issue by Aghneel** [Winfredy/SadTalker#8]
Is that possible to adapt this for cartoon/anime faces or this is just for human faces?

**Comment by vinthony** [comment]
Hi, our method works for generating realistic 3d faces and then utilizing them for driving human faces via a 3d-aware generator.

Thus, it is easy to apply the generated 3d facial landmarks~(from 3dmm render) for cartoon/anime faces talking-head generation via the following  wonderful projects:

1. cartoon face part of makeittalk:
https://github.com/yzhou359/MakeItTalk#animate-you-portraits

2.  anime talking-head-geneartion methods:
https://github.com/pkhungurn/talking-head-anime-2-demo
https://github.com/pkhungurn/talking-head-anime-demo


Since it needs a lot of code to merge, we will continues update our projects to include these options.

**Comment by Aghneel** [comment]
I didn't know about those projects! Thank you for the answer and great work!
